const shopTypes = {
  GET_SHOP_DATA: "GET_SHOP_DATA",
  GET_EXIST_DATA: "GET_EXIST_DATA",
  GET_CATEGORY_DATA: "GET_CATEGORY_DATA",
  GET_SHOP_DATA_SCROLL: "GET_SHOP_DATA_SCROLL",
  ADD_SHOP_DATA: "ADD_SHOP_DATA",
  UPDATE_SHOP_DATA: "UPDATE_SHOP_DATA",
  DELETE_SHOP_DATA: "DELETE_SHOP_DATA",
};

export default shopTypes;
