const favouriteTypes ={
    ADD_FAVOURITE_ITEM:'ADD_FAVOURITE_ITEM',
    REMOVE_FAVOURITE_ITEM:'REMOVE_FAVOURITE_ITEM',
    FIND_FAVOURITE_ITEM : 'FIND_FAVOURITE_ITEM',
    ADD_WISHLIST_ITEM : 'ADD_WISHLIST_ITEM',
    CLEAR_WISHLIST :"CLEAR_WISHLIST" 
}
export default favouriteTypes;